### PR TITLE
Russian translation

### PR DESCRIPTION
**Pull request by Aldrog**

### CODE REVIEW

**Comment by Aldrog** [comment]
I found "Choose a color" in settings and "Icon URL" in bookmark editor are not marked as translatabe.

**Comment by tim-sueberkrueb** [comment]
@Aldrog thank you very much, I fixed the missing strings.

**Comment by Aldrog** [comment]
Well, now it only adds two files of updated translation.
I wish there was an easier way to keep a fork up-to-date with upstream than manual merging (or there is?).

**Comment by tim-sueberkrueb** [comment]
@Aldrog thanks! Yes, but merging manually should only be needed when incompatible changes happen to master (which was my fault because I changed that line in material-browser.pro). Should I credit you (e.g. by creating something like contributors.md)?

**Comment by tim-sueberkrueb** [comment]
Created https://github.com/tim-sueberkrueb/material-browser/blob/master/CONTRIBUTORS.md

**Comment by Aldrog** [comment]
@tim-sueberkrueb I don't mind if you do and most likely you will need something like this anyway because there will be a lot of contributions in future.

**Comment by tim-sueberkrueb** [comment]
@Aldrog hopefully :) Is the format okay?

**Comment by Aldrog** [comment]
@tim-sueberkrueb it's nice :)

**Pull request merged**
