### PR TITLE
A browser icon.

### PR DESCRIPTION
**Pull request by overhound**
I rendered a material design browser icon that you could use for the project.

### CODE REVIEW

**Comment by tim-sueberkrueb** [comment]
@overhound Looks like I was too late :) nice icon anyway

**Comment by overhound** [comment]
You could use it, I've hit a road block on my project that I don't think I can overcome... I'm happy to send a push request again if you really want it?

**Comment by tim-sueberkrueb** [comment]
@overhound The icon is beautiful. The only reason why we probably can't use it nevertheless is that we're going to change the name, otherwise I'd like to use it immediately  :/ … so it's fine if you use it for your own project. Thank you for your offer though and good luck for finding a workaround for the blocker if that's possible :)

**Comment by overhound** [comment]
Alright it's no problem at all, if by the time you come up with a name you still don't have an icon, let me know and I'll be happy to render one for you

**Comment by tim-sueberkrueb** [comment]
@overhound Wow, thanks, that'd be great :)

**Pull request closed without merging**
